services:
  trax-web:
    build: .
    container_name: trax-platform
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=0
      - SECRET_KEY=${SECRET_KEY}