services:
  trax-web:
    build: .
    container_name: trax-platform
    ports:
      - "5000:5000"
    volumes:
    - .:/app
    - trax_instance:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
volumes:
  trax_instance: