"""Destructive PostgreSQL validation for partial operation_commands schemas."""

import os
import sys
import unittest
from contextlib import contextmanager
from pathlib import Path

import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from sqlalchemy.engine import make_url


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))
POSTGRES_URL = os.environ.get("TRAX_POSTGRES_TEST_URL")
ALLOW_RESET = os.environ.get("TRAX_POSTGRES_TEST_ALLOW_RESET") == "1"


class PostgreSQLOperationCommandPartialMigrationTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not POSTGRES_URL:
            raise RuntimeError("TRAX_POSTGRES_TEST_URL es obligatorio")
        if make_url(POSTGRES_URL).get_backend_name() not in ("postgresql", "postgres"):
            raise RuntimeError("La URL de pruebas debe apuntar a PostgreSQL")
        if not ALLOW_RESET:
            raise RuntimeError("TRAX_POSTGRES_TEST_ALLOW_RESET=1 es obligatorio")
        cls.engine = sa.create_engine(POSTGRES_URL, pool_pre_ping=True)

    @classmethod
    def tearDownClass(cls):
        cls.engine.dispose()

    def setUp(self):
        with self.engine.begin() as connection:
            connection.execute(sa.text("DROP SCHEMA public CASCADE"))
            connection.execute(sa.text("CREATE SCHEMA public"))
        self._alembic("upgrade", "20260726_01")

    @contextmanager
    def _migration_environment(self):
        old_database_url = os.environ.get("DATABASE_URL")
        old_secret = os.environ.get("SECRET_KEY")
        os.environ["DATABASE_URL"] = POSTGRES_URL
        os.environ["SECRET_KEY"] = "postgres-partial-migration"
        try:
            yield
        finally:
            if old_database_url is None:
                os.environ.pop("DATABASE_URL", None)
            else:
                os.environ["DATABASE_URL"] = old_database_url
            if old_secret is None:
                os.environ.pop("SECRET_KEY", None)
            else:
                os.environ["SECRET_KEY"] = old_secret

    def _alembic(self, action, revision):
        config = Config(str(PROJECT_ROOT / "alembic.ini"))
        with self._migration_environment():
            getattr(command, action)(config, revision)

    def _revision(self):
        with self.engine.connect() as connection:
            return connection.execute(
                sa.text("SELECT version_num FROM alembic_version")
            ).scalar_one()

    def _create_partial(
        self,
        actor_type="INTEGER",
        actor_nullable=False,
        generator="identity",
        sequence_options="",
    ):
        nullable = "" if actor_nullable else " NOT NULL"
        if generator == "identity":
            id_definition = (
                "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            )
        elif generator == "none":
            id_definition = "INTEGER PRIMARY KEY"
        elif generator == "owned_sequence":
            with self.engine.begin() as connection:
                connection.execute(
                    sa.text(
                        "CREATE SEQUENCE operation_commands_existing_seq "
                        + sequence_options
                    )
                )
            id_definition = (
                "INTEGER PRIMARY KEY DEFAULT "
                "nextval('operation_commands_existing_seq'::regclass)"
            )
        elif generator == "missing_sequence":
            id_definition = (
                "INTEGER PRIMARY KEY DEFAULT "
                "nextval('operation_commands_missing_seq'::text)"
            )
        elif generator == "foreign_sequence":
            with self.engine.begin() as connection:
                connection.execute(
                    sa.text("CREATE SEQUENCE operation_commands_foreign_seq")
                )
            id_definition = (
                "INTEGER PRIMARY KEY DEFAULT "
                "nextval('operation_commands_foreign_seq'::regclass)"
            )
        else:
            raise ValueError(f"Generator desconocido: {generator}")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    f"""
                    CREATE TABLE operation_commands (
                        id {id_definition},
                        actor_user_id {actor_type}{nullable},
                        operation VARCHAR(80) NOT NULL,
                        idempotency_key VARCHAR(160) NOT NULL,
                        payload_hash VARCHAR(64) NOT NULL,
                        status VARCHAR(20) NOT NULL,
                        result_entity_type VARCHAR(80),
                        result_entity_id INTEGER,
                        correlation_id VARCHAR(36) NOT NULL,
                        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                        completed_at TIMESTAMP WITHOUT TIME ZONE,
                        failure_code VARCHAR(80)
                    )
                    """
                )
            )
            if generator == "owned_sequence":
                connection.execute(
                    sa.text(
                        "ALTER SEQUENCE operation_commands_existing_seq "
                        "OWNED BY operation_commands.id"
                    )
                )

    def _insert_user(self, suffix):
        with self.engine.begin() as connection:
            return connection.execute(
                sa.text(
                    "INSERT INTO users (nombre, email, password, rol, estado) "
                    "VALUES ('PK Test', :email, 'hash', 'CLIENTE', 'ACTIVO') "
                    "RETURNING id"
                ),
                {"email": f"pk-{suffix}@test.local"},
            ).scalar_one()

    def _insert_command_without_id(self, actor_id, key):
        with self.engine.begin() as connection:
            return connection.execute(
                sa.text(
                    "INSERT INTO operation_commands "
                    "(actor_user_id, operation, idempotency_key, payload_hash, "
                    "status, correlation_id, created_at) "
                    "VALUES (:actor_id, 'CREATE_DIRECT_CONTRACT', :key, "
                    ":payload_hash, 'PROCESSING', "
                    "'00000000-0000-0000-0000-000000000099', now()) "
                    "RETURNING id"
                ),
                {
                    "actor_id": actor_id,
                    "key": key,
                    "payload_hash": "0" * 64,
                },
            ).scalar_one()

    def _insert_command_with_id(self, actor_id, command_id, key):
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "INSERT INTO operation_commands "
                    "(id, actor_user_id, operation, idempotency_key, payload_hash, "
                    "status, correlation_id, created_at) "
                    "VALUES (:command_id, :actor_id, 'CREATE_DIRECT_CONTRACT', "
                    ":key, :payload_hash, 'PROCESSING', "
                    "'00000000-0000-0000-0000-000000000098', now())"
                ),
                {
                    "command_id": command_id,
                    "actor_id": actor_id,
                    "key": key,
                    "payload_hash": "9" * 64,
                },
            )

    def _sequence_parameters(self, name="operation_commands_existing_seq"):
        with self.engine.connect() as connection:
            parameters = dict(
                connection.execute(
                    sa.text(
                        "SELECT increment_by, min_value, max_value, cycle "
                        "FROM pg_sequences "
                        "WHERE schemaname = current_schema() "
                        "AND sequencename = :name"
                    ),
                    {"name": name},
                ).mappings().one()
            )
            state = connection.execute(
                sa.text(
                    f"SELECT last_value, is_called FROM {name}"
                )
            ).mappings().one()
        parameters.update(
            last_value=int(state["last_value"]),
            is_called=bool(state["is_called"]),
        )
        parameters["effective_next"] = (
            int(parameters["last_value"]) + int(parameters["increment_by"])
            if parameters["is_called"]
            else int(parameters["last_value"])
        )
        return parameters

    def _assert_complete(self):
        inspector = sa.inspect(self.engine)
        columns = {
            column["name"]: column
            for column in inspector.get_columns("operation_commands")
        }
        self.assertEqual(len(columns), 12)
        self.assertFalse(columns["actor_user_id"]["nullable"])
        self.assertIn(
            "fk_operation_commands_actor_user_id",
            {
                item["name"]
                for item in inspector.get_foreign_keys("operation_commands")
            },
        )
        self.assertIn(
            "uq_operation_commands_actor_operation_key",
            {
                item["name"]
                for item in inspector.get_unique_constraints("operation_commands")
            },
        )
        self.assertIn(
            "ck_operation_commands_status",
            {
                item["name"]
                for item in inspector.get_check_constraints("operation_commands")
            },
        )
        self.assertTrue(
            {
                "ix_operation_commands_actor_user_id",
                "ix_operation_commands_correlation_id",
            }.issubset(
                {
                    item["name"]
                    for item in inspector.get_indexes("operation_commands")
                }
            )
        )

    def test_empty_table_with_missing_columns_is_repaired(self):
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "CREATE TABLE operation_commands "
                    "(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)"
                )
            )

        self._alembic("upgrade", "20260726_02")

        self.assertEqual(self._revision(), "20260726_02")
        self._assert_complete()

    def test_nullable_and_missing_constraints_are_repaired(self):
        self._create_partial(actor_nullable=True)

        self._alembic("upgrade", "20260726_02")

        self._assert_complete()

    def test_incompatible_type_blocks_transactionally_without_data_loss(self):
        self._create_partial(actor_type="VARCHAR(50)")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "INSERT INTO operation_commands "
                    "(actor_user_id, operation, idempotency_key, payload_hash, status, "
                    "correlation_id, created_at) "
                    "VALUES ('bad', 'CREATE', 'pg-partial-key-0001', :payload_hash, "
                    "'PROCESSING', '00000000-0000-0000-0000-000000000001', now())"
                ),
                {"payload_hash": "0" * 64},
            )

        with self.assertRaises(RuntimeError):
            self._alembic("upgrade", "20260726_02")

        self.assertEqual(self._revision(), "20260726_01")
        inspector = sa.inspect(self.engine)
        self.assertNotIn(
            "contracting_mode",
            {column["name"] for column in inspector.get_columns("contract_requests")},
        )
        with self.engine.connect() as connection:
            self.assertEqual(
                connection.execute(
                    sa.text("SELECT COUNT(*) FROM operation_commands")
                ).scalar_one(),
                1,
            )

    def test_upgrade_and_partial_downgrade_are_restartable(self):
        self._alembic("upgrade", "20260726_02")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text("DROP INDEX ix_operation_commands_correlation_id")
            )

        self._alembic("downgrade", "20260726_01")
        self.assertEqual(self._revision(), "20260726_01")
        self.assertFalse(sa.inspect(self.engine).has_table("operation_commands"))

        self._alembic("upgrade", "20260726_02")
        self._assert_complete()

    def test_pk_without_generator_empty_table_is_repaired(self):
        self._create_partial(generator="none")

        self._alembic("upgrade", "20260726_02")

        actor_id = self._insert_user("empty")
        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-pk-empty-0001"),
            1,
        )

    def test_pk_without_generator_with_existing_data_advances_after_max(self):
        self._create_partial(generator="none")
        actor_id = self._insert_user("existing")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "INSERT INTO operation_commands "
                    "(id, actor_user_id, operation, idempotency_key, payload_hash, "
                    "status, correlation_id, created_at) "
                    "VALUES (41, :actor_id, 'CREATE_DIRECT_CONTRACT', "
                    "'pg-existing-id-0001', :payload_hash, 'PROCESSING', "
                    "'00000000-0000-0000-0000-000000000041', now())"
                ),
                {"actor_id": actor_id, "payload_hash": "1" * 64},
            )

        self._alembic("upgrade", "20260726_02")

        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-after-existing-0001"),
            42,
        )

    def test_existing_owned_sequence_is_advanced_above_max_id(self):
        self._create_partial(generator="owned_sequence")
        actor_id = self._insert_user("desync")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "INSERT INTO operation_commands "
                    "(id, actor_user_id, operation, idempotency_key, payload_hash, "
                    "status, correlation_id, created_at) "
                    "VALUES (50, :actor_id, 'CREATE_DIRECT_CONTRACT', "
                    "'pg-desync-id-0001', :payload_hash, 'PROCESSING', "
                    "'00000000-0000-0000-0000-000000000050', now())"
                ),
                {"actor_id": actor_id, "payload_hash": "2" * 64},
            )
            connection.execute(
                sa.text(
                    "SELECT setval('operation_commands_existing_seq', 1, false)"
                )
            )

        self._alembic("upgrade", "20260726_02")

        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-after-desync-0001"),
            51,
        )

    def test_descending_owned_sequence_is_normalized_before_insert(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY -1 MINVALUE 1 MAXVALUE 100 "
                "START WITH 100 NO CYCLE"
            ),
        )
        actor_id = self._insert_user("descending")
        self._insert_command_with_id(actor_id, 49, "pg-descending-0049")
        self._insert_command_with_id(actor_id, 50, "pg-descending-0050")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "SELECT setval('operation_commands_existing_seq', 50, true)"
                )
            )

        before = self._sequence_parameters()
        self.assertEqual(before["increment_by"], -1)
        self.assertEqual(before["effective_next"], 49)

        self._alembic("upgrade", "20260726_02")

        after = self._sequence_parameters()
        self.assertEqual(after["increment_by"], 1)
        self.assertEqual(after["min_value"], 1)
        self.assertEqual(after["max_value"], 2147483647)
        self.assertFalse(after["cycle"])
        self.assertEqual(after["effective_next"], 51)
        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-descending-fixed"),
            51,
        )

    def test_negative_increment_is_normalized(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY -2 MINVALUE 1 MAXVALUE 100 "
                "START WITH 100 NO CYCLE"
            ),
        )
        actor_id = self._insert_user("negative-increment")
        self._insert_command_with_id(actor_id, 10, "pg-negative-0010")

        self._alembic("upgrade", "20260726_02")

        after = self._sequence_parameters()
        self.assertEqual(after["increment_by"], 1)
        self.assertEqual(after["effective_next"], 11)
        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-negative-fixed"),
            11,
        )

    def test_cycle_enabled_is_disabled(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY 1 MINVALUE 1 MAXVALUE 100 "
                "START WITH 1 CYCLE"
            ),
        )
        actor_id = self._insert_user("cycle")
        self._insert_command_with_id(actor_id, 10, "pg-cycle-0010")

        self._alembic("upgrade", "20260726_02")

        after = self._sequence_parameters()
        self.assertFalse(after["cycle"])
        self.assertEqual(after["effective_next"], 11)

    def test_insufficient_max_value_is_expanded_safely(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY 1 MINVALUE 1 MAXVALUE 50 "
                "START WITH 1 NO CYCLE"
            ),
        )
        actor_id = self._insert_user("small-max")
        self._insert_command_with_id(actor_id, 50, "pg-small-max-0050")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "SELECT setval('operation_commands_existing_seq', 50, true)"
                )
            )

        self._alembic("upgrade", "20260726_02")

        after = self._sequence_parameters()
        self.assertEqual(after["max_value"], 2147483647)
        self.assertEqual(after["effective_next"], 51)
        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-small-max-fixed"),
            51,
        )

    def test_incompatible_min_value_is_normalized(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY 1 MINVALUE 40 MAXVALUE 100 "
                "START WITH 40 NO CYCLE"
            ),
        )
        actor_id = self._insert_user("high-min")
        self._insert_command_with_id(actor_id, 50, "pg-high-min-0050")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "SELECT setval('operation_commands_existing_seq', 50, true)"
                )
            )

        self._alembic("upgrade", "20260726_02")

        after = self._sequence_parameters()
        self.assertEqual(after["min_value"], 1)
        self.assertEqual(after["effective_next"], 51)

    def test_effective_next_value_that_would_collide_is_restarted(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 "
                "START WITH 1 NO CYCLE"
            ),
        )
        actor_id = self._insert_user("near-collision")
        self._insert_command_with_id(actor_id, 50, "pg-near-collision-0050")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "SELECT setval('operation_commands_existing_seq', 49, true)"
                )
            )
        self.assertEqual(self._sequence_parameters()["effective_next"], 50)

        self._alembic("upgrade", "20260726_02")

        self.assertEqual(self._sequence_parameters()["effective_next"], 51)
        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-collision-fixed"),
            51,
        )

    def test_semantically_compatible_existing_sequence_is_preserved(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 "
                "START WITH 1 NO CYCLE"
            ),
        )
        actor_id = self._insert_user("compatible")
        self._insert_command_with_id(actor_id, 50, "pg-compatible-0050")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "SELECT setval('operation_commands_existing_seq', 50, true)"
                )
            )
        before = self._sequence_parameters()

        self._alembic("upgrade", "20260726_02")

        after = self._sequence_parameters()
        self.assertEqual(after, before)
        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-compatible-next"),
            51,
        )

    def test_integer_exhaustion_blocks_before_any_phase2a_mutation(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 "
                "START WITH 1 NO CYCLE"
            ),
        )
        actor_id = self._insert_user("exhausted")
        self._insert_command_with_id(
            actor_id,
            2147483647,
            "pg-exhausted-2147483647",
        )
        before = self._sequence_parameters()

        with self.assertRaises(RuntimeError):
            self._alembic("upgrade", "20260726_02")

        self.assertEqual(self._revision(), "20260726_01")
        self.assertEqual(self._sequence_parameters(), before)
        with self.engine.connect() as connection:
            self.assertEqual(
                connection.execute(
                    sa.text("SELECT MAX(id) FROM operation_commands")
                ).scalar_one(),
                2147483647,
            )
        self.assertNotIn(
            "contracting_mode",
            {
                column["name"]
                for column in sa.inspect(self.engine).get_columns(
                    "contract_requests"
                )
            },
        )

    def test_shared_owned_sequence_blocks_without_mutation(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY -1 MINVALUE 1 MAXVALUE 100 "
                "START WITH 100 NO CYCLE"
            ),
        )
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "CREATE TABLE sequence_consumer ("
                    "id INTEGER DEFAULT "
                    "nextval('operation_commands_existing_seq'::regclass))"
                )
            )
        before = self._sequence_parameters()

        with self.assertRaises(RuntimeError):
            self._alembic("upgrade", "20260726_02")

        self.assertEqual(self._revision(), "20260726_01")
        self.assertEqual(self._sequence_parameters(), before)

    def test_default_pointing_to_missing_sequence_is_replaced(self):
        self._create_partial(generator="missing_sequence")
        actor_id = self._insert_user("missing")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "INSERT INTO operation_commands "
                    "(id, actor_user_id, operation, idempotency_key, payload_hash, "
                    "status, correlation_id, created_at) "
                    "VALUES (60, :actor_id, 'CREATE_DIRECT_CONTRACT', "
                    "'pg-missing-seq-0001', :payload_hash, 'PROCESSING', "
                    "'00000000-0000-0000-0000-000000000060', now())"
                ),
                {"actor_id": actor_id, "payload_hash": "3" * 64},
            )

        self._alembic("upgrade", "20260726_02")

        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-after-missing-0001"),
            61,
        )

    def test_unowned_existing_sequence_is_blocked_without_appropriation(self):
        self._create_partial(generator="foreign_sequence")

        with self.assertRaises(RuntimeError):
            self._alembic("upgrade", "20260726_02")

        self.assertEqual(self._revision(), "20260726_01")
        with self.engine.connect() as connection:
            self.assertIsNotNone(
                connection.execute(
                    sa.text(
                        "SELECT to_regclass('operation_commands_foreign_seq')"
                    )
                ).scalar_one()
            )

    def test_generator_repair_is_reentrant(self):
        self._create_partial(generator="none")
        self._alembic("upgrade", "20260726_02")
        with self.engine.begin() as connection:
            connection.execute(
                sa.text(
                    "UPDATE alembic_version SET version_num = '20260726_01'"
                )
            )

        self._alembic("upgrade", "20260726_02")

        actor_id = self._insert_user("reentrant")
        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-reentrant-0001"),
            1,
        )

    def test_downgrade_drops_owned_sequence_and_new_upgrade_generates_ids(self):
        self._alembic("upgrade", "20260726_02")
        with self.engine.begin() as connection:
            connection.execute(sa.text("CREATE SEQUENCE unrelated_foreign_seq"))
        self._alembic("downgrade", "20260726_01")
        with self.engine.connect() as connection:
            self.assertIsNone(
                connection.execute(
                    sa.text(
                        "SELECT to_regclass('operation_commands_id_seq')"
                    )
                ).scalar_one()
            )
            self.assertIsNotNone(
                connection.execute(
                    sa.text("SELECT to_regclass('unrelated_foreign_seq')")
                ).scalar_one()
            )
            self.assertIsNone(
                connection.execute(
                    sa.text(
                        "SELECT to_regclass('operation_commands_id_phase2a_seq')"
                    )
                ).scalar_one()
            )

        self._alembic("upgrade", "20260726_02")
        actor_id = self._insert_user("downgrade")
        self.assertEqual(
            self._insert_command_without_id(actor_id, "pg-after-downgrade-0001"),
            1,
        )

    def test_downgrade_preserves_preexisting_owned_sequence(self):
        self._create_partial(
            generator="owned_sequence",
            sequence_options=(
                "AS INTEGER INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 "
                "START WITH 1 NO CYCLE"
            ),
        )
        self._alembic("upgrade", "20260726_02")

        self._alembic("downgrade", "20260726_01")

        with self.engine.connect() as connection:
            self.assertIsNotNone(
                connection.execute(
                    sa.text(
                        "SELECT to_regclass('operation_commands_existing_seq')"
                    )
                ).scalar_one()
            )


if __name__ == "__main__":
    unittest.main(verbosity=2)
